In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [3]:
MAT = torch.tensor([[i for i in range(10)] for l in range(10)])
MAT

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [4]:
MAT.ndim

2

In [5]:
RANDOM_TENSOR = torch.rand((4,5,2))

In [6]:
RANDOM_TENSOR

tensor([[[0.4067, 0.2821],
         [0.9694, 0.5648],
         [0.6068, 0.2422],
         [0.6885, 0.0889],
         [0.1664, 0.8059]],

        [[0.6550, 0.5503],
         [0.3923, 0.7500],
         [0.0743, 0.8027],
         [0.7237, 0.6752],
         [0.6137, 0.7360]],

        [[0.8277, 0.6785],
         [0.7840, 0.0201],
         [0.2379, 0.0780],
         [0.8087, 0.8207],
         [0.5928, 0.3629]],

        [[0.3443, 0.8334],
         [0.6081, 0.5081],
         [0.6915, 0.7985],
         [0.8018, 0.2082],
         [0.8393, 0.4780]]])

In [7]:
ZEROS_TENSOR = torch.zeros((4,5,2))
ZEROS_TENSOR

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [8]:
ONES_TENSOR = torch.ones((4,5,2))
ONES_TENSOR

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [9]:
ID_TENSOR = torch.eye(4, 5)
ID_TENSOR

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [10]:
RANGE_VALUES_TENSOR = torch.arange(0,10)
RANGE_VALUES_TENSOR

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ZEROES_TENSOR_LIKE = torch.zeros_like(RANGE_VALUES_TENSOR)
ZEROES_TENSOR_LIKE

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
ONES_TENSOR_LIKE = torch.ones_like(RANGE_VALUES_TENSOR)
ONES_TENSOR_LIKE

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## The Most Common Errors In Tensor Manipulation

1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on right device.



```
TEST = torch.tensor([1, 2, 6],
                    dtype= 'torch.float32' or 'torch.float16' or 'torch.float64'
                    device= 'cpu' or 'cuda'
                    requeries_grad= True or False)
```



In [13]:
torch.matmul(RANGE_VALUES_TENSOR, ONES_TENSOR_LIKE)

tensor(45)

In [14]:
def matrixMul(Mat1, Mat2):
  if Mat1.shape[1] == Mat2.shape[0]:
    RESULT = []
    for line1 in Mat1:
      LINE = []
      for line2 in Mat2.T:
        line = line1 * line2
        LINE.append(sum(line))
      RESULT.append(LINE)
      LINE = []
    return torch.tensor(RESULT)
  else:
    return "Can't Multiply, Not right shape"

In [15]:
tensor1 = torch.tensor([[2,1],[5,9]])
tensor2 = torch.tensor([[2,1],[5,9]])

In [16]:
%%time
matrixMul(tensor1, tensor2)

CPU times: user 1.63 ms, sys: 115 µs, total: 1.75 ms
Wall time: 6 ms


tensor([[ 9, 11],
        [55, 86]])

In [17]:
%%time
tensor1.matmul(tensor2)

CPU times: user 668 µs, sys: 767 µs, total: 1.44 ms
Wall time: 4.35 ms


tensor([[ 9, 11],
        [55, 86]])

* Reshape(): Reshapes the tensor into another shape that's compatibale to make.
* View(): Same as reshape but shares the memory with the original tensor, like BDD.
* Squeeze(): Removes dimensions with 1 like (1,2,4) -> (2,4).
* Unsqueeze(): Adds 1 dimension at dim=x.
* Stack(): Concatenate tensors like v1, v2, v3 -> (v1, v2, v3).
* Permute(): 

In [18]:
tensor1 = tensor1.reshape((1,4))
tensor2 = tensor2.reshape((1,4))

In [19]:
torch.stack((tensor1, tensor2), dim=1).shape

torch.Size([1, 2, 4])

In [20]:
tensor1 = torch.tensor([[2,1,9],[5,9,2]])
tensor2 = torch.tensor([[2,4,6],[4,9,0]])
tensor = torch.stack((tensor1, tensor2), dim=1)
tensor

tensor([[[2, 1, 9],
         [2, 4, 6]],

        [[5, 9, 2],
         [4, 9, 0]]])

In [21]:
tensor.shape

torch.Size([2, 2, 3])

In [22]:
torch.from_numpy(tensor.numpy())

tensor([[[2, 1, 9],
         [2, 4, 6]],

        [[5, 9, 2],
         [4, 9, 0]]])

In [23]:
!nvidia-smi

Mon Dec 26 18:12:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    26W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [24]:
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

In [25]:
# Move Tensor To GPU
tensor_gpu = tensor.to('cuda')

In [26]:
tensor_gpu

tensor([[[2, 1, 9],
         [2, 4, 6]],

        [[5, 9, 2],
         [4, 9, 0]]], device='cuda:0')

In [27]:
# Tensor in GPU moved into CPU
tensor_gpu.cpu()

tensor([[[2, 1, 9],
         [2, 4, 6]],

        [[5, 9, 2],
         [4, 9, 0]]])